#!/usr/bin/env bash
#
# Copyright (C) 2016 Xenith Consulting Limited
# Author: Salim Badakhchani <sadakhc@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Switch on Debugging
set -x

# Define logfile
LOG="/root/install.log"

echo -e "########################################################################" > ${LOG}
echo -e "Installing System..." >> ${LOG}
echo -e "########################################################################\n" >> ${LOG}
echo -e $(date) >> ${LOG}
echo >> ${LOG}

# Execution statements logically grouped into functions.
function system_update {
    echo -e "# Updating system..." >> ${LOG}
    yum -y update > /dev/null 2>&1
}

install_deps () {
    
    echo -e "# Installing dependencies..." >> ${LOG}
    yum -y install httpd mariadb-server mariadb mlocate php php-mysql php-fpm patch rysnc htop

    echo -e "# Starting services..." >> ${LOG}
    systemctl start httpd.service
    systemctl enable httpd.service
    systemctl start mariadb.service
    systemctl enable mariadb.service
   
    echo -e "# Creating dadatbases..." >> ${LOG}
    mysql -u root -Bse "CREATE DATABASE wordpress; CREATE USER wpadmin@localhost IDENTIFIED BY 'WpDbAdm00'; GRANT ALL PRIVILEGES ON wordpress.* TO wpadmin@localhost IDENTIFIED BY 'WpDbAdm00'; FLUSH PRIVILEGES; exit"

    echo -e "# Securing MySql..." >> ${LOG} 
    echo -e "\n\nMySqlAdm00\nMySqlAdm00\n\n\nn\n\n " | mysql_secure_installation 2>/dev/null

    systemctl restart mariadb.service
    systemctl restart httpd.service
}

install_wordpress () {
    
    cd ~
    wget http://wordpress.org/latest.tar.gz
    tar xzvf latest.tar.gz
    rsync -avP ~/wordpress/ /var/www/html/
    mkdir -p  /var/www/html/wp-content/uploads
    chown -R apache:apache /var/www/html/
    chown -R root:root /var/www/html/wp-admin

    echo -e "# Patching PHP..." >> ${LOG} 
    cp -p /etc/php.ini /etc/php.ini.orig
    cat > /tmp/php.ini.patch << 'EOF'
--- /etc/php.ini    2016-05-12 13:49:38.000000000 +0000
+++ /etc/php.ini    2016-06-21 12:10:20.975267701 +0000
@@ -797,7 +797,7 @@
 
 ; Maximum allowed size for uploaded files.
 ; http://php.net/upload-max-filesize
-upload_max_filesize = 2M
+upload_max_filesize = 48M
 
 ; Maximum number of files that can be uploaded via a single request
 max_file_uploads = 20

EOF
    (cd / && patch -p0) < /tmp/php.ini.patch
    rm -f /tmp/php.ini.patch

    echo -e "# Patching Wordpress..." >> ${LOG}        
    cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
    cat > /tmp/wp-config.php.patch << 'EOF'
--- /var/www/html/wp-config.php	2015-12-16 09:58:26.000000000 +0000
+++ /var/www/html/wp-config.php	2016-07-03 23:17:07.898866778 +0000
@@ -20,13 +20,13 @@
 
 // ** MySQL settings - You can get this info from your web host ** //
 /** The name of the database for WordPress */
-define('DB_NAME', 'database_name_here');
+define('DB_NAME', 'wordpress');
 
 /** MySQL database username */
-define('DB_USER', 'username_here');
+define('DB_USER', 'wpadmin');
 
 /** MySQL database password */
-define('DB_PASSWORD', 'password_here');
+define('DB_PASSWORD', 'WpDbAdm00');
 
 /** MySQL hostname */
 define('DB_HOST', 'localhost');

EOF
    (cd / && patch -p0) < /tmp/wp-config.php.patch
    rm -f /tmp/wp-config.php.patch
    chown -R apache:apache /var/www/html/
    chown -R root:root /var/www/html/wp-admin
}

post_install () {

    echo -e "# Running post install..." >> ${LOG}
    updatedb
    hostnamectl set-hostname srv01.arisim.consuling
    systemctl restart mariadb.service
    systemctl restart httpd.service
}

install_deps
install_wordpress
post_install
