#!/usr/bin/env bash
#
# Copyright (C) 2016 Xenith Consulting Limited
# Author: Salim Badakhchani <sadakhc@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Switch on Debugging
set -x

# Define logfile
LOG="/root/install.log"

echo -e "########################################################################" > $LOG
echo -e "Installing System..." >> $LOG
echo -e "########################################################################\n" >> $LOG
echo -e $(date) >> $LOG
echo >> $LOG

# Non-interactive mode
export DEBIAN_FRONTEND=noninteractive

# Execution statements logicaly grouped into functions.
function system_update {
    echo -e "# Updating system..." >> $LOG
    apt-get update > /dev/null 2>&1
}

function install_deps {
    
    echo -e "# Installing tools..." >> $LOG
    apt-get -y install build-essential software-properties-common iotop mytop iftop htop mc vim wget tmux debconf-utils git curl tree auditd> /dev/null 2>&1

    echo -e "# Install mail server..." >> $LOG
    hostnamectl set-hostname localhost
    debconf-set-selections <<< "postfix postfix/mailname string localhost"
    debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
    apt-get -y install mailutils > /dev/null 2>&1
    dpkg-reconfigure debconf -f noninteractive

}

function cleanup {
    echo -e "# Cleaning up" >> $LOG
    apt-get clean > /dev/null 2>&1
}

function install_ftpd {
    echo -e "Installing vsftpd" >> $LOG
    apt-get install vsftpd
    cp -p /etc/vsftpd.conf /etc/vsftpd.conf.orig 
    sed -i 's/anonymous_enable=NO/anonymous_enable=YES/' /etc/vsftpd.conf
    systemctl restart vsftpd
}

function send_notification {
    echo -e "# DEPSRV Installation completed. System Rebooted" >> $LOG
    aureport | mail -s "New Host Notification" sbadakhc@gmail.com
    reboot 
}

# Execute functions 
system_update
install_deps
install_ftpd
cleanup
send_notification
